export const tpls = {
  tpl1: {
    background: "rgba(255,255,255,1)",
    version: "4.5.1",
    objects: [
      {
        type: "image",
        // version: "4.5.1",
        // originX: "left",
        // originY: "top",
        // left: 0,
        // top: 0,
        width: 600,
        height: 800,
        // fill: "rgb(0,0,0)",
        // stroke: null,
        // strokeWidth: 0,
        // strokeDashArray: null,
        // strokeLineCap: "butt",
        // strokeDashOffset: 0,
        // strokeLineJoin: "miter",
        // strokeUniform: false,
        // strokeMiterLimit: 4,
        // scaleX: 1,
        // scaleY: 1,
        // angle: 0,
        // flipX: false,
        // flipY: false,
        // opacity: 1,
        // shadow: null,
        // visible: true,
        // backgroundColor: "",
        // fillRule: "nonzero",
        // paintFirst: "fill",
        // globalCompositeOperation: "source-over",
        // skewX: 0,
        // skewY: 0,
        // cropX: 0,
        // cropY: 0,
        src: "https://s1.ax1x.com/2022/09/22/xFBHyj.jpg",
        // crossOrigin: null,
        // filters: [],
        cursorStyle: "default",
        selectable: false, // 背景图不可选择
        hasBorders: false, //不显示选中时的边
        hasControls: false, //不显示控制的那9个按钮
        lockMovementX: true,
        lockMovementY: true,
        hoverCursor: "defalut"
      },
      {
        type: "textbox",
        version: "4.5.1",
        originX: "left",
        originY: "top",
        left: 26,
        top: 34.33,
        width: 195.53,
        height: 45.2,
        fill: "#06c",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "示例书名",
        fontSize: 40,
        fontWeight: "normal",
        fontFamily: "Times New Roman",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        direction: "ltr",
        styles: {},
        editable: false
      },
      {
        type: "textbox",
        version: "4.5.1",
        originX: "left",
        originY: "top",
        left: 59,
        top: 164.33,
        width: 195.53,
        height: 45.2,
        fill: "#06c",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        text: "作者名称",
        fontSize: 28,
        fontWeight: "normal",
        fontFamily: "Times New Roman",
        fontStyle: "normal",
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "left",
        textBackgroundColor: "",
        charSpacing: 0,
        path: null,
        direction: "ltr",
        styles: {},
        editable: false
      },
    ],
    tplImgs:
      "https://cdn.wtzw.com/bookimg/public/images/cover/a3c6/c1ed18f83a0de69814ac2ee0201260d4_360x480.jpg",
  },
  tpl2: {
    background: "rgba(255,255,255,1)",
    version: "4.5.1",
    objects: [],
    tplImgs:
      "https://cdn.wtzw.com/bookimg/public/images/cover/a3c6/c1ed18f83a0de69814ac2ee0201260d4_360x480.jpg",
  },
  tpl3: {
    background: "rgba(255,255,255,1)",
    version: "4.5.1",
    objects: [],
    tplImgs:
      "https://cdn.wtzw.com/bookimg/public/images/cover/a3c6/c1ed18f83a0de69814ac2ee0201260d4_360x480.jpg",
  },
  tpl4: {
    background: "rgba(255,255,255,1)",
    version: "4.5.1",
    objects: [],
    tplImgs:
      "https://cdn.wtzw.com/bookimg/public/images/cover/a3c6/c1ed18f83a0de69814ac2ee0201260d4_360x480.jpg",
  },
};
// const tpls = {
//     "json": {
//         "version": "4.5.1",
//         "objects": [
//             {
//                 "type": "image",
//                 "version": "4.5.1",
//                 "originX": "left",
//                 "originY": "top",
//                 "left": 0,
//                 "top": 0,
//                 "width": 600,
//                 "height": 800,
//                 "fill": "rgb(0,0,0)",
//                 "stroke": null,
//                 "strokeWidth": 0,
//                 "strokeDashArray": null,
//                 "strokeLineCap": "butt",
//                 "strokeDashOffset": 0,
//                 "strokeLineJoin": "miter",
//                 "strokeUniform": false,
//                 "strokeMiterLimit": 4,
//                 "scaleX": 0.5,
//                 "scaleY": 0.5,
//                 "angle": 0,
//                 "flipX": false,
//                 "flipY": false,
//                 "opacity": 1,
//                 "shadow": null,
//                 "visible": true,
//                 "backgroundColor": "",
//                 "fillRule": "nonzero",
//                 "paintFirst": "fill",
//                 "globalCompositeOperation": "source-over",
//                 "skewX": 0,
//                 "skewY": 0,
//                 "cropX": 0,
//                 "cropY": 0,
//                 "src": "",
//                 "crossOrigin": null,
//                 "filters": [ ]
//             },
//             {
//                 "type": "i-text",
//                 "version": "4.5.1",
//                 "originX": "left",
//                 "originY": "top",
//                 "left": 26,
//                 "top": 34.33,
//                 "width": 195.53,
//                 "height": 45.2,
//                 "fill": "#06c",
//                 "stroke": null,
//                 "strokeWidth": 1,
//                 "strokeDashArray": null,
//                 "strokeLineCap": "butt",
//                 "strokeDashOffset": 0,
//                 "strokeLineJoin": "miter",
//                 "strokeUniform": false,
//                 "strokeMiterLimit": 4,
//                 "scaleX": 1,
//                 "scaleY": 1,
//                 "angle": 0,
//                 "flipX": false,
//                 "flipY": false,
//                 "opacity": 1,
//                 "shadow": null,
//                 "visible": true,
//                 "backgroundColor": "",
//                 "fillRule": "nonzero",
//                 "paintFirst": "fill",
//                 "globalCompositeOperation": "source-over",
//                 "skewX": 0,
//                 "skewY": 0,
//                 "text": "H5-Dooring",
//                 "fontSize": 40,
//                 "fontWeight": "normal",
//                 "fontFamily": "Times New Roman",
//                 "fontStyle": "normal",
//                 "lineHeight": 1.16,
//                 "underline": false,
//                 "overline": false,
//                 "linethrough": false,
//                 "textAlign": "left",
//                 "textBackgroundColor": "",
//                 "charSpacing": 0,
//                 "path": null,
//                 "direction": "ltr",
//                 "styles": { }
//             },
//             {
//                 "type": "i-text",
//                 "version": "4.5.1",
//                 "originX": "left",
//                 "originY": "top",
//                 "left": 59,
//                 "top": 164.33,
//                 "width": 195.53,
//                 "height": 45.2,
//                 "fill": "#06c",
//                 "stroke": null,
//                 "strokeWidth": 1,
//                 "strokeDashArray": null,
//                 "strokeLineCap": "butt",
//                 "strokeDashOffset": 0,
//                 "strokeLineJoin": "miter",
//                 "strokeUniform": false,
//                 "strokeMiterLimit": 4,
//                 "scaleX": 1,
//                 "scaleY": 1,
//                 "angle": 0,
//                 "flipX": false,
//                 "flipY": false,
//                 "opacity": 1,
//                 "shadow": null,
//                 "visible": true,
//                 "backgroundColor": "",
//                 "fillRule": "nonzero",
//                 "paintFirst": "fill",
//                 "globalCompositeOperation": "source-over",
//                 "skewX": 0,
//                 "skewY": 0,
//                 "text": "H5-Dooring",
//                 "fontSize": 40,
//                 "fontWeight": "normal",
//                 "fontFamily": "Times New Roman",
//                 "fontStyle": "normal",
//                 "lineHeight": 1.16,
//                 "underline": false,
//                 "overline": false,
//                 "linethrough": false,
//                 "textAlign": "left",
//                 "textBackgroundColor": "",
//                 "charSpacing": 0,
//                 "path": null,
//                 "direction": "ltr",
//                 "styles": { }
//             }
//         ],
//         "background": "rgba(255,255,255,1)"
//     },
//         "t": "1"
//     },
//     "CnWeeUnV": {
//     "json": {
//         "version": "4.5.1",
//         "objects": [
//             {
//                 "type": "image",
//                 "version": "4.5.1",
//                 "originX": "left",
//                 "originY": "top",
//                 "left": 0,
//                 "top": 0,
//                 "width": 600,
//                 "height": 800,
//                 "fill": "rgb(0,0,0)",
//                 "stroke": null,
//                 "strokeWidth": 0,
//                 "strokeDashArray": null,
//                 "strokeLineCap": "butt",
//                 "strokeDashOffset": 0,
//                 "strokeLineJoin": "miter",
//                 "strokeUniform": false,
//                 "strokeMiterLimit": 4,
//                 "scaleX": 0.5,
//                 "scaleY": 0.5,
//                 "angle": 0,
//                 "flipX": false,
//                 "flipY": false,
//                 "opacity": 1,
//                 "shadow": null,
//                 "visible": true,
//                 "backgroundColor": "",
//                 "fillRule": "nonzero",
//                 "paintFirst": "fill",
//                 "globalCompositeOperation": "source-over",
//                 "skewX": 0,
//                 "skewY": 0,
//                 "cropX": 0,
//                 "cropY": 0,
//                 "src": "",
//                 "crossOrigin": null,
//                 "filters": [ ]
//             },
//             {
//                 "type": "i-text",
//                 "version": "4.5.1",
//                 "originX": "left",
//                 "originY": "top",
//                 "left": 24,
//                 "top": 42.33,
//                 "width": 195.53,
//                 "height": 45.2,
//                 "fill": "#06c",
//                 "stroke": null,
//                 "strokeWidth": 1,
//                 "strokeDashArray": null,
//                 "strokeLineCap": "butt",
//                 "strokeDashOffset": 0,
//                 "strokeLineJoin": "miter",
//                 "strokeUniform": false,
//                 "strokeMiterLimit": 4,
//                 "scaleX": 1,
//                 "scaleY": 1,
//                 "angle": 0,
//                 "flipX": false,
//                 "flipY": false,
//                 "opacity": 1,
//                 "shadow": null,
//                 "visible": true,
//                 "backgroundColor": "",
//                 "fillRule": "nonzero",
//                 "paintFirst": "fill",
//                 "globalCompositeOperation": "source-over",
//                 "skewX": 0,
//                 "skewY": 0,
//                 "text": "H5-Dooring",
//                 "fontSize": 40,
//                 "fontWeight": "normal",
//                 "fontFamily": "Times New Roman",
//                 "fontStyle": "normal",
//                 "lineHeight": 1.16,
//                 "underline": false,
//                 "overline": false,
//                 "linethrough": false,
//                 "textAlign": "left",
//                 "textBackgroundColor": "",
//                 "charSpacing": 0,
//                 "path": null,
//                 "direction": "ltr",
//                 "styles": { }
//             },
//             {
//                 "type": "i-text",
//                 "version": "4.5.1",
//                 "originX": "left",
//                 "originY": "top",
//                 "left": 36,
//                 "top": 138.33,
//                 "width": 195.53,
//                 "height": 45.2,
//                 "fill": "#06c",
//                 "stroke": null,
//                 "strokeWidth": 1,
//                 "strokeDashArray": null,
//                 "strokeLineCap": "butt",
//                 "strokeDashOffset": 0,
//                 "strokeLineJoin": "miter",
//                 "strokeUniform": false,
//                 "strokeMiterLimit": 4,
//                 "scaleX": 1,
//                 "scaleY": 1,
//                 "angle": 0,
//                 "flipX": false,
//                 "flipY": false,
//                 "opacity": 1,
//                 "shadow": null,
//                 "visible": true,
//                 "backgroundColor": "",
//                 "fillRule": "nonzero",
//                 "paintFirst": "fill",
//                 "globalCompositeOperation": "source-over",
//                 "skewX": 0,
//                 "skewY": 0,
//                 "text": "H5-Dooring",
//                 "fontSize": 40,
//                 "fontWeight": "normal",
//                 "fontFamily": "Times New Roman",
//                 "fontStyle": "normal",
//                 "lineHeight": 1.16,
//                 "underline": false,
//                 "overline": false,
//                 "linethrough": false,
//                 "textAlign": "left",
//                 "textBackgroundColor": "",
//                 "charSpacing": 0,
//                 "path": null,
//                 "direction": "ltr",
//                 "styles": { }
//             }
//         ],
//         "background": "rgba(255,255,255,1)"
//     },
//     "t": "2"
// }
// }
